name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v**']
  workflow_dispatch:
jobs:
  package:
    name: Package binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate binaries for macOS, Linux and Windows
        run: npm run package
      - name: Rename macOS binary to conform to GitHub CLI extension rules
        run: mv bin/migrate-project-macos bin/gh-migrate-project-darwin-amd64
      - name: Rename Windows binary to conform to GitHub CLI extension rules
        run: mv bin/migrate-project-win.exe bin/gh-migrate-project-windows-amd64.exe
      - name: Rename Linux binary to conform to GitHub CLI extension rules
        run: mv bin/migrate-project-linux bin/gh-migrate-project-linux-amd64
      - name: Upload macOS binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-macos
          path: bin/gh-migrate-project-darwin-amd64
      - name: Upload Linux binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-linux
          path: bin/gh-migrate-project-linux-amd64
      - name: Upload Windows binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-windows
          path: bin/gh-migrate-project-windows-amd64.exe
  create_release:
    name: Create release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: 'package'
    permissions:
      contents: write
    steps:
      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: package-windows
          path: bin
      - name: Download macOS binary
        uses: actions/download-artifact@v4
        with:
          name: package-macos
          path: bin
      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: package-linux
          path: bin
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/gh-migrate-project-darwin-amd64
            bin/gh-migrate-project-linux-amd64
            bin/gh-migrate-project-windows-amd64.exe
          generate_release_notes: true

